version: 0.2

env:
  shell: bash
  variables:
    MEND_URL: "https://saas.mend.io"
    MEND_EMAIL: "saasmend-joshrup-ci@mend.io"
    MEND_USER_KEY: "a881046f0c0348e7b6e275a314bb11182a794b7a0a8e46d596ac131836ee4f8f"


phases:
  pre_build:
    commands:
      - curl https://downloads.mend.io/cli/linux_amd64/mend -o ./mend && chmod +x ./mend
  build:
    commands:
        # The scan should be called AFTER a package manager build step such as "mvn clean install -DskipTests=true" or "npm install --only=prod"
       - npm install
  post_build:
    commands:
       - export repo=$(basename -s .git $(git config --get remote.origin.url))
       - export branch=$(git rev-parse --abbrev-ref HEAD)
       - echo 'Run Mend dependencies scan'
       - ./mend sca -u -s *//${repo}//${branch} --non-interactive --export-results dep-results.txt
       - echo 'Start Mend Code Scan'
       - ./mend sast  --non-interactive -s *//${repo}//${branch}
